server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Використовуємо змінну оточення з дефолтним значенням
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/spa-realm}